site_name: PHP Chess API
site_url: https://chess-api.docs.chesslablab.org/
nav:
  - Home: index.md
  - Installation: installation.md
  - Endpoints:
    - GET /v1/annotations/games: get-annotations-games.md
    - GET /v1/autocomplete/event: get-autocomplete-event.md
    - GET /v1/autocomplete/player: get-autocomplete-player.md
    - GET /v1/stats/opening: get-stats-opening.md
    - POST /v1/download/image: post-download-image.md
    - POST /v1/download/mp4: post-download-mp4.md
    - POST /v1/heuristics: post-heuristics.md
    - POST /v1/search: post-search.md
    - POST /v1/stats/event: post-stats-event.md
    - POST /v1/stats/player: post-stats-player.md
    - POST /v1/play/rav: post-play-rav.md
theme: readthedocs
