v1_annotations_games:
    path:       /v1/annotations/games
    controller: ChessApi\Controller\AnnotationsGamesController::index
    methods:    OPTIONS|GET

v1_autocomplete_event:
    path:       /v1/autocomplete/event
    controller: ChessApi\Controller\AutocompleteEventController::index
    methods:    OPTIONS|POST

v1_autocomplete_player:
    path:       /v1/autocomplete/player
    controller: ChessApi\Controller\AutocompletePlayerController::index
    methods:    OPTIONS|POST

v1_download_image:
    path:       /v1/download/image
    controller: ChessApi\Controller\DownloadImageController::index
    methods:    OPTIONS|POST

v1_download_mp4:
    path:       /v1/download/mp4
    controller: ChessApi\Controller\DownloadMp4Controller::index
    methods:    OPTIONS|POST

v1_eval_names:
    path:       /v1/eval/names
    controller: ChessApi\Controller\EvalNamesController::index
    methods:    OPTIONS|POST

v1_heuristic:
    path:       /v1/heuristic
    controller: ChessApi\Controller\HeuristicController::index
    methods:    OPTIONS|POST

v1_play_rav:
    path:       /v1/play/rav
    controller: ChessApi\Controller\PlayRavController::index
    methods:    OPTIONS|POST

v1_search:
    path:       /v1/search
    controller: ChessApi\Controller\SearchController::index
    methods:    OPTIONS|POST

v1_stats_event:
    path:       /v1/stats/event
    controller: ChessApi\Controller\StatsEventController::index
    methods:    OPTIONS|POST

v1_stats_opening:
    path:       /v1/stats/opening
    controller: ChessApi\Controller\StatsOpeningController::index
    methods:    OPTIONS|GET

v1_stats_player:
    path:       /v1/stats/player
    controller: ChessApi\Controller\StatsPlayerController::index
    methods:    OPTIONS|POST

v1_tutor_fen:
    path:       /v1/tutor/fen
    controller: ChessApi\Controller\TutorFenController::index
    methods:    OPTIONS|POST

v1_tutor_good_move:
    path:       /v1/tutor/good-move
    controller: ChessApi\Controller\TutorGoodMoveController::index
    methods:    OPTIONS|POST
